#PBS -N CIFAR_Tests

#PBS -l select=1:ncpus=1:mem=12gb
#PBS -l Walltime=72:00:00
#PBS -j oe
#PBS -o CIFAR_Tests_Secure_Federated.txt

cd /home/dlangbe/Thesis/CIFAR


# inputs are fout, learning_rate, num_epochs, num_filters, filter_size, num_nodes, batch_size, conv_layers, secure
./cnn output.txt 0.001 4 8 3 2 100 1 1
./cnn output.txt 0.001 4 8 3 4 100 1 1
./cnn output.txt 0.001 4 8 3 8 50 1 1
./cnn output.txt 0.001 4 8 3 16 25 1 1
