#PBS -N S_Learn_R

#PBS -l select=1:ncpus=1:mem=12gb
#PBS -l Walltime=72:00:00
#PBS -j oe
#PBS -o MNIST_Tests_Secure_Learning_Rate.txt

cd /home/dlangbe/Thesis/MNIST


# inputs are fout, learning_rate, num_epochs, num_filters, filter_size, num_nodes, batch_size, conv_layers, secure
./cnn output.txt 0.001 4 8 3 1 100 1 1
./cnn output.txt 0.002 4 8 3 1 100 1 1
./cnn output.txt 0.003 4 8 3 1 100 1 1
./cnn output.txt 0.004 4 8 3 1 100 1 1
./cnn output.txt 0.005 4 8 3 1 100 1 1
./cnn output.txt 0.006 4 8 3 1 100 1 1
./cnn output.txt 0.007 4 8 3 1 100 1 1
./cnn output.txt 0.008 4 8 3 1 100 1 1
./cnn output.txt 0.009 4 8 3 1 100 1 1
./cnn output.txt 0.01 4 8 3 1 100 1 1
