#PBS -N S_L_rate

#PBS -l select=1:ncpus=1:mem=12gb
#PBS -l Walltime=48:00:00
#PBS -j oe
#PBS -o MNIST_Test_Secure_Learing_Rate_New.txt

cd /home/dlangbe/Thesis/MNIST

make

# inputs are fout, learning_rate, num_epochs, num_filters, filter_size, num_nodes, batch_size, conv_layers, secure
./cnn output.txt 0.001 8 8 3 1 100 1 1
./cnn output.txt 0.002 8 8 3 1 100 1 1
./cnn output.txt 0.003 8 8 3 1 100 1 1
./cnn output.txt 0.004 8 8 3 1 100 1 1
./cnn output.txt 0.005 8 8 3 1 100 1 1
./cnn output.txt 0.006 8 8 3 1 100 1 1
./cnn output.txt 0.007 8 8 3 1 100 1 1
./cnn output.txt 0.008 8 8 3 1 100 1 1
./cnn output.txt 0.009 8 8 3 1 100 1 1
./cnn output.txt 0.01 8 8 3 1 100 1 1
